package org.sakaiproject.contentreview2;

import java.util.UUID;

/**
 * Review generated by the content review system.
 */
public class Review {
    /**
     * Unique identifier of the submission, can also be used as the unique identifier of the review.
     */
    private final String submissionId;

    /**
     * Creates a review for the given submission.
     *
     * @param submissionId identifier of the submission.
     */
    public Review(String submissionId) {
        this.submissionId = submissionId;
    }

    /**
     * Creates a review and generates its submission id.
     *
     * @see #Review(String)
     */
    public Review() {
        this(UUID.randomUUID().toString());
    }

    public String getSubmissionId() {
        return submissionId;
    }
}
